version: "3.8"

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
      - ./backend/staticfiles:/usr/src/app/staticfiles
      - ./media:/app/media
    ports:
      - "8000:8000"
    env_file:  # ✅ Ensure Django reads environment variables from .env
      - .env
    depends_on:
      - redis
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py collectstatic --noinput &&
            python manage.py runserver 0.0.0.0:8000"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: >
      sh -c "npm install && npm run dev"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  celery_worker:
    build: ./backend
    volumes:
      - ./media:/app/media
    env_file:  # ✅ Add this to ensure Celery uses the same DB as Django
      - .env
    command: >
      sh -c "sleep 10 && celery -A edutechai worker --loglevel=info"
    depends_on:
      - redis
      - backend

  celery_beat:
    build: ./backend
    env_file:  # ✅ Add this to ensure Celery uses the same DB as Django
      - .env
    command: >
      sh -c "sleep 15 && celery -A edutechai beat --loglevel=info"
    depends_on:
      - redis
      - backend
      - celery_worker
