version: "3.8"

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: edutechai
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
      build: ./backend
      volumes:
        - ./backend:/usr/src/app
        - ./backend/staticfiles:/usr/src/app/staticfiles
        - /Users/claudiovalletta/Documents/EdutechAI/backend/media:/app/media  # Mount absolute path
        - ./backend/media:/app/media
      ports:
        - "8000:8000"
      env_file:
        - .env
      depends_on:
        - db
        - redis
      command: >
        sh -c "python manage.py wait_for_db &&
              python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py collectstatic --noinput &&
              python manage.py runserver 0.0.0.0:8000"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: >
      sh -c "npm install && npm run dev"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  celery_worker:
    build: ./backend
    volumes:
      - /Users/claudiovalletta/Documents/EdutechAI/backend/media:/app/media  # Mount absolute path
    env_file:
      - .env
    command: >
      sh -c "sleep 10 && celery -A edutechai worker --loglevel=info"
    depends_on:
      - redis
      - backend
      - db

  celery_beat:
    build: ./backend
    env_file:
      - .env
    command: >
      sh -c "sleep 15 && celery -A edutechai beat --loglevel=info"
    depends_on:
      - redis
      - backend
      - celery_worker
      - db

volumes:
  postgres_data:
