# Generated by Django 5.1.5 on 2025-02-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='background_color',
            field=models.CharField(default='#ffffff', help_text='Hex color code for the background (e.g., #ff0000 for red).', max_length=7),
        ),
    ]
