# Generated by Django 5.1.5 on 2025-02-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_lessonresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonresource',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
