# Generated by Django 5.1.5 on 2025-02-15 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_lessonresource_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonresource',
            name='resource_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('audio', 'Audio'), ('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('other', 'Other')], default='other', max_length=10),
        ),
    ]
