# Generated by Django 5.1.5 on 2025-02-15 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_lessonresource_resource_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lessonresource',
            table='app_lessonresource',
        ),
    ]
