# Generated by Django 5.1.5 on 2025-02-16 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_lessonresource_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonresource',
            name='entities',
        ),
        migrations.RemoveField(
            model_name='lessonresource',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='lessonresource',
            name='topics',
        ),
        migrations.AddField(
            model_name='lessonresource',
            name='subject',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='MonthlyAPIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('gemini', 'Google Gemini'), ('azure_tts', 'Azure Text-to-Speech')], max_length=20)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_input_tokens', models.IntegerField(default=0)),
                ('total_output_tokens', models.IntegerField(default=0)),
                ('total_characters_processed', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'service', 'month', 'year')},
            },
        ),
    ]
