# Generated by Django 5.1.5 on 2025-02-27 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_keyconcepts'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='backgrounds/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='background_color',
        ),
        migrations.AddField(
            model_name='project',
            name='background_type',
            field=models.CharField(choices=[('preset', 'Preset Image'), ('color', 'Color Gradient')], default='preset', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='gradient_end',
            field=models.CharField(blank=True, help_text='End color hex (e.g., #ffff00 for yellow).', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='gradient_start',
            field=models.CharField(blank=True, help_text='Start color hex (e.g., #ff0000 for red).', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='background_image',
            field=models.ForeignKey(blank=True, help_text='Choose a predefined background image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='app.backgroundimage'),
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='app.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
