# Generated by Django 5.1.5 on 2025-02-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_backgroundimage_remove_project_background_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
