# Generated by Django 5.1.5 on 2025-02-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_project_background_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonresource',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
