# Generated by Django 5.1.5 on 2025-02-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_lessonresource_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonresource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
