# Generated by Django 5.1.5 on 2025-03-01 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_lessonresource_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyconcepts',
            name='title',
        ),
    ]
