# Generated by Django 5.1.5 on 2025-03-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_keyconcepts_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='word_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
