# Generated by Django 5.1.5 on 2025-03-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_summary_word_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='content',
            field=models.JSONField(),
        ),
    ]
