# Generated by Django 5.1.5 on 2025-03-09 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_summary_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='word_count',
        ),
    ]
