# Generated by Django 5.1.5 on 2025-03-09 22:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('TRIAL', 'Trial'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='TRIAL', help_text='Tipo di abbonamento', max_length=10)),
                ('start_date', models.DateField(default=django.utils.timezone.now, help_text="Data di inizio dell'abbonamento o del trial")),
                ('expiry_date', models.DateField(blank=True, help_text="Data di scadenza dell'abbonamento o del trial", null=True)),
                ('is_active', models.BooleanField(default=True, help_text="Indica se l'abbonamento è attivo")),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='rest_duration',
            field=models.PositiveIntegerField(default=5, help_text='Durata della pausa in minuti (default: 5)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='theme',
            field=models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', help_text="Tema preferito dell'utente", max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='work_duration',
            field=models.PositiveIntegerField(default=25, help_text='Durata della sessione di lavoro in minuti (default: 25)'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Importo del pagamento', max_digits=10)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Data e ora del pagamento')),
                ('payment_method', models.CharField(choices=[('CREDIT_CARD', 'Credit Card'), ('PAYPAL', 'PayPal'), ('BANK_TRANSFER', 'Bank Transfer')], help_text='Metodo di pagamento utilizzato', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='ID della transazione (se disponibile)', max_length=100, null=True, unique=True)),
                ('user', models.ForeignKey(help_text='Utente associato al pagamento', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, help_text='Abbonamento associato al pagamento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='app.subscription')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription',
            field=models.OneToOneField(blank=True, help_text="Abbonamento dell'utente", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='app.subscription'),
        ),
    ]
