# Generated by Django 5.1.5 on 2025-04-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_mentionedperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentionedperson',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentionedperson',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
